#!/bin/bash
# Remote CLI for ScreenInvader by @burnoutberni

screeninvaderurl="http://10.20.30.40"

function add() { curl -s "$screeninvaderurl/cgi-bin/show?$1" -o /dev/null; }

function play() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerPause" -o /dev/null; }
function pause() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerPause" -o /dev/null; }
function stop() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerClose" -o /dev/null; }
function next() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerNext" -o /dev/null; }
function previous() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerPrevious" -o /dev/null; }
function forward() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerForward" -o /dev/null; }
function rewind() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerRewind" -o /dev/null; }
function forwardmore() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerForwardMore" -o /dev/null; }
function rewindmore() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerRewindMore" -o /dev/null; }

function volume() {
	if [ "$1" -le "100" -a "$1" -ge "0" ]; then
		curl "$screeninvaderurl/cgi-bin/set?/sound/volume=$1"
		echo "[SUCCESS] Volume set to $1"
	else
		echo "[ERROR] Set volume to a value between 0 and 100"
	fi
}

function close() { curl -s "$screeninvaderurl/cgi-bin/trigger?browserClose" -o /dev/null; }
function pageup() { curl -s "$screeninvaderurl/cgi-bin/trigger?browserPageUp" -o /dev/null; }
function pagedown() { curl -s "$screeninvaderurl/cgi-bin/trigger?browserPageDown" -o /dev/null; }
function scrollup() { curl -s "$screeninvaderurl/cgi-bin/trigger?browserScrollUp" -o /dev/null; }
function scrolldown() { curl -s "$screeninvaderurl/cgi-bin/trigger?browserScrollDown" -o /dev/null; }
function zoomin() { curl -s "$screeninvaderurl/cgi-bin/trigger?browserZoomIn" -o /dev/null; }
function zoomout() { curl -s "$screeninvaderurl/cgi-bin/trigger?browserZoomOut" -o /dev/null; }

if [ $# -eq 0 ]; then
	printf " ScreenInvader CLI\n
 Usage:
  add [url] – add new item to playlist or open browser\n
  play/pause – toggle play/pause
  stop – stop player
  next/previous – jump to next/previous item
  forward[more]/rewind[more] – forward and rewind [with extra speed]\n
  volume [0-100] – set volume\n
  close – close browser
  pageup/pagedown – page up/page down
  scrollup/scrolldown – scroll up/scroll down
  zoomin/zoomout – zoom in/out\n"
fi

$@


