#!/bin/bash
# Remote CLI for ScreenInvader by @burnoutberni

screeninvaderurl="http://10.20.30.40"

function add() { curl -s "$screeninvaderurl/cgi-bin/show?$1" -o /dev/null; }
function play() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerPause" -o /dev/null; }
function pause() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerPause" -o /dev/null; }
function stop() { curl -s "$screeninvaderurl/cgi-bin/trigger?playerClose" -o /dev/null; }
function volume() {
	if [ "$1" -le "100" -a "$1" -ge "0" ]; then
		curl "$screeninvaderurl/cgi-bin/set?/sound/volume=$1"
		echo "[SUCCESS] Volume set to $1"
	else
		echo "[ERROR] Set volume to a value between 0 and 100"
	fi
}

if [ $# -eq 0 ]; then
	printf " ScreenInvader CLI\n
 Usage:
  add [url] – add new item to playlist or open browser
  play/pause – toggle play/pause
  stop – stop player
  volume [0-100] – set volume\n"
fi

$@


